M48
; DRILL file {KiCad 9.0.2} date 2025-07-08T14:50:56+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-07-08T14:50:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X77.16Y-104.46
X131.0Y-107.0
X151.0Y-65.0
X174.0Y-94.0
X206.29Y-84.81
M30
